services:
  - type: web
    name: invest-master-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_DEFAULT_USER
        value: "0"
